service_web/contabilidad/urls.py
# @Author: Manuel Rodriguez <valle>
# @Date:   01-Jan-2018
# @Email:  valle.mrv@gmail.com
# @Last modified by:   valle
# @Last modified time: 09-Jan-2018
# @License: Apache license vesion 2.0

from django.conf.urls import url, include
from . import views

GASTOS = [
    url(r"^gastos/$", views.gastos, name="gastos"),
    url(r"^elegir_cuenta/$", views.elegir_cuenta, name="elegir_cuenta"),
    url(r"^gastos/(?P<id>-?\d*)/$", views.gastos, name="gastos"),
    url(r"^lista_gastos/$", views.lista_gastos, name="lista_gastos"),
    url(r"^find_cuentas/$", views.find_cuentas, name="find_cuentas"),
    url(r"^rm_gasto/(?P<id>\d*)$", views.rm_gasto, name="rm_gasto"),
    url(r"^find_gasto/$", views.find_gasto, name="find_gasto"),

]

INGRESOS = [
    url(r"^ingresos/$", views.ingresos, name="ingresos"),
    url(r"^ingresos/(?P<id>-?\d*)/$", views.ingresos, name="ingresos"),
    url(r"^lista_ingresos/$", views.lista_ingresos, name="lista_ingresos"),
    url(r"^find_ingreso/$", views.find_ingreso, name="find_ingreso"),
    url(r"^rm_ingreso/(?P<id>\d*)$", views.rm_ingreso, name="rm_ingreso"),
    url(r"^calcular_ingreso/(?P<fecha>\d*)$", views.calcular_ingreso, name="calcular_ingreso"),
    url(r"^calcular_ingreso/$", views.calcular_ingreso, name="calcular_ingreso_none"),
]


ALBARANES = [
    url(r"^albaranes/$", views.albaranes, name="albaranes_none"),
    url(r"^al_elegir_proveedor/$", views.al_elegir_proveedor, name="al_elegir_proveedor"),
    url(r"^albaranes/(?P<id>-?\d*)/$", views.albaranes, name="albaranes"),
    url(r"^lista_albaranes/$", views.lista_albaranes, name="lista_albaranes"),
    url(r"^find_albaran/$", views.find_albaran, name="find_albaranes"),
    url(r"^rm_albaran/(?P<id>\d*)$", views.rm_albaran, name="rm_albaranes"),
    url(r"^view_doc_albaran/(?P<id>\d*)$", views.view_doc_albaran, name="view_doc_albaran"),
    url(r"^viewer_img_albaran/(?P<id>\d*)$", views.viewer_img_albaran, name="viewer_img_albaran"),
    url(r"^find_albaran/$", views.find_albaran, name="find_albaran"),
]


PROVEEDORES = [
    url(r"^proveedores/$", views.proveedores, name="proveedores"),
    url(r"^proveedores/(?P<id>\d*)/$", views.proveedores, name="proveedores"),
    url(r"^lista_proveedores/$", views.lista_proveedores, name="lista_proveedores"),
    url(r"^find_proveedores/$", views.find_proveedores, name="find_proveedores"),
    url(r"^rm_proveedores/(?P<id>\d*)$", views.rm_proveedores, name="rm_proveedores"),
    url(r"^set_proveedor/(?P<id>\d*)$", views.set_proveedor, name="set_proveedor"),
    url(r"^set_proveedor/$", views.set_proveedor, name="set_proveedor_none"),
    url(r"^salir_proveedores/$", views.salir_proveedores, name="salir_proveedores"),
]

CUENTAS = [
    url(r"^cuentas/$", views.cuentas, name="cuentas"),
    url(r"^cuentas/(?P<id>\d*)/$", views.cuentas, name="cuentas"),
    url(r"^lista_cuentas/$", views.lista_cuentas, name="lista_cuentas"),
    url(r"^find_cuentas/$", views.find_cuentas, name="find_cuentas"),
    url(r"^rm_cuentas/(?P<id>\d*)$", views.rm_cuentas, name="rm_cuenta"),
    url(r"^set_cuenta/(?P<id>\d*)$", views.set_cuenta, name="set_cuenta"),
    url(r"^set_cuenta/$", views.set_cuenta, name="set_cuenta"),
    url(r"^salir_cuentas/$", views.salir_cuentas, name="salir_cuentas"),
]

SUBCUENTAS = [
    url(r"^subcuentas/$", views.subcuentas, name="subcuentas"),
    url(r"^subcuentas/(?P<id>\d*)/$", views.subcuentas, name="subcuentas"),
    url(r"^lista_subcuentas/$", views.lista_subcuentas, name="lista_subcuentas"),
    url(r"^find_subcuentas/$", views.find_subcuentas, name="find_subcuentas"),
    url(r"^rm_subcuentas/(?P<id>\d*)$", views.rm_subcuentas, name="rm_subcuenta"),
    url(r"^set_subcuenta/(?P<id>\d*)$", views.set_subcuenta, name="set_subcuenta"),
    url(r"^set_subcuenta/$", views.set_subcuenta, name="set_subcuenta"),
    url(r"^salir_subcuentas/$", views.salir_cuentas, name="salir_subcuentas"),
]

urlpatterns = [
    url(r"^$", views.inicio, name="inicio")
]+ PROVEEDORES + ALBARANES + CUENTAS + GASTOS + INGRESOS + SUBCUENTAS

service_web/inicio/urls.py
# @Author: Manuel Rodriguez <valle>
# @Date:   01-Jan-2018
# @Email:  valle.mrv@gmail.com
# @Last modified by:   valle
# @Last modified time: 04-Jan-2018
# @License: Apache license vesion 2.0

from django.conf.urls import url, include
from . import views

USER = [
    url(r'^login/$', views.login, name="login_tk"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^change_password/$', views.change_password, name="change_password"),
    url(r'^reset_password/$', views.reset_password, name="password_reset"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.confirm_reset_password, name='password_reset_confirm'),
]


urlpatterns = [
    url(r'^$', views.menu_principal, name="menu_principal"),
    url(r'^not_found/$', views.not_found, name="not_found"),
    url(r'^en_construccion/$', views.en_construccion, name="en_construccion")
] + USER

service_web/contabilidad/models.py
# -*- coding: utf-8 -*-

# @Author: Manuel Rodriguez <valle>
# @Date:   01-Jan-2018
# @Email:  valle.mrv@gmail.com
# @Last modified by:   valle
# @Last modified time: 09-Jan-2018
# @License: Apache license vesion 2.0

from __future__ import unicode_literals
from django.db import models

# Create your models here.

class Proveedores(models.Model):
    nombre = models.CharField(max_length=100)
    razon_social = models.CharField("Razón social", max_length=100,  blank=True, null=True)
    CIF = models.CharField(max_length=10,  blank=True, null=True)
    direccion = models.CharField("Dirección", max_length=100, blank=True, null=True)
    telefono = models.CharField(max_length=12, blank=True, null=True)
    notas = models.TextField(null=True, blank=True)
    activo = models.BooleanField(default=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        ordering = ["-id"]


class CuentasGastos(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField("Descripción", null=True, blank=True)
    activo = models.BooleanField(default=True)

    def __unicode__(self):
        return self.nombre

    class Meta:
        ordering = ["-id"]

class SubCuentaGastos(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField("Descripción", null=True, blank=True)
    gastos = models.ManyToManyField("Gastos")
    cuenta = models.ForeignKey("CuentasGastos", on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)

    def __unicode__(self):
        return self.nombre


    class Meta:
        ordering = ["-id"]


class Gastos(models.Model):
    importe = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.CharField("Descripción", max_length=150, null=True, blank=True)
    cuenta = models.ForeignKey("CuentasGastos", on_delete=models.CASCADE)
    fecha_apunte = models.DateTimeField(auto_now_add=True)
    fecha_modificado = models.DateField(auto_now=True)
    fecha = models.DateField()
    pagado = models.BooleanField(default=True)

    def __unicode__(self):
        return self.descripcion

    class Meta:
        ordering = ["-fecha"]


class Albaranes(models.Model):
    importe = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.CharField("Descripción", max_length=150, null=True, blank=True)
    fecha_apunte = models.DateTimeField(auto_now_add=True)
    fecha = models.DateField()
    fecha_modificado = models.DateField(auto_now=True)
    doc = models.FileField(upload_to='albaranes', null=True, blank=True)
    cuenta = models.ForeignKey("Proveedores", on_delete=models.CASCADE)
    aviso = models.CharField("Aviso", max_length=150, null=True, blank=True)
    pagado = models.BooleanField(default=False)

    def __unicode__(self):
        return self.descripcion

    class Meta:
        ordering = ["-fecha"]

class Facturas(models.Model):
    albaranes = models.ManyToManyField("Albaranes")
    fecha_apunte = models.DateTimeField(auto_now_add=True)
    fecha = models.DateField()
    fecha_modificado = models.DateField(auto_now=True)
    doc = models.FileField(upload_to='facturas', null=True, blank=True)

    class Meta:
        ordering = ["-fecha"]

class SaldoRegulador(models.Model):
    importe = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.CharField(max_length=150)
    fecha_apunte = models.DateTimeField(auto_now_add=True)
    fecha_modificado = models.DateField(auto_now=True)
    cuenta = models.ForeignKey("Proveedores", on_delete=models.CASCADE)

    class Meta:
        ordering = ["-fecha_apunte"]



class Ingresos(models.Model):
    importe = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.CharField("Descripción", max_length=50, default="Caja del dia")
    fecha = models.DateField()
    fecha_apunte = models.DateTimeField(auto_now_add=True)
    fecha_modificado = models.DateField(auto_now=True)

    class Meta:
        ordering = ["-fecha_apunte"]

service_web/contabilidad/forms.py
# -*- coding: utf-8 -*-

# @Author: Manuel Rodriguez <valle>
# @Date:   03-Jan-2018
# @Email:  valle.mrv@gmail.com
# @Last modified by:   valle
# @Last modified time: 08-Jan-2018
# @License: Apache license vesion 2.0


from django import forms
from models import *

class ProveedoresForm(forms.ModelForm):

    class Meta:
        model = Proveedores
        exclude = ["activo"]


class AlbaranForm(forms.ModelForm):
    class Meta:
        model = Albaranes
        exclude = ["cuenta"]



class GastosForm(forms.ModelForm):
    class Meta:
        model = Gastos
        exclude = ["cuenta"]


class CuentasGastosForm(forms.ModelForm):
    class Meta:
        model = CuentasGastos
        exclude = ["activo"]
        widgets = {
            "descripcion": forms.TextInput()
        }

class SaldoReguladorForm(forms.ModelForm):
    class Meta:
        model = SaldoRegulador
        exclude = []

class IngresosForm(forms.ModelForm):
    class Meta:
        model = Ingresos
        exclude = []

class SubCuentaGastosForm(forms.ModelForm):
    class Meta:
        model = SubCuentaGastos
        exclude = ["gastos", "activo"]

service_web/contabilidad/views/alabaranes.py
# -*- coding: utf-8 -*-

# @Author: Manuel Rodriguez <valle>
# @Date:   01-Jan-2018
# @Email:  valle.mrv@gmail.com
# @Last modified by:   valle
# @Last modified time: 09-Jan-2018
# @License: Apache license vesion 2.0

from django.db.models import Q
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from contabilidad.models import Albaranes, Proveedores
from contabilidad.forms import AlbaranForm
from datetime import datetime
import os

# Create your views here.
@login_required(login_url='login_tk')
def al_elegir_proveedor(request):
    filter_query = Albaranes.objects.filter(Q(fecha__month=datetime.now().strftime("%m")))
    return render(request, "contabilidad/albaranes/find_proveedor.html",
                  {'query': filter_query,
                   'proveedor': 'si'})

@login_required(login_url='login_tk')
def albaranes(request, id=-1):
    id = int(id)
    p = get_proveedor_activo(request)
    filter_query = Albaranes.objects.filter(Q(cuenta_id=p.pk))
    if not request.method == "POST" and id == -1:
        f = AlbaranForm()
        return render(request, 'contabilidad/albaranes/listado.html',
                      {"form": f,
                       "p": p,
                       "pk": id,
                       'query': filter_query,
                       "mensaje": "Albaran nuevo" })

    elif not request.method == "POST" and id > 0:
        f = AlbaranForm()
        try:
            obj = Albaranes.objects.get(pk=id)
            f = AlbaranForm(instance=obj)
        except:
            pass
        return render(request, 'contabilidad/albaranes/listado.html',
                      {"form": f,
                       "p": p,
                       "pk": id,
                       'query': filter_query,
                       "mensaje": "Editar albaran" })
    elif id > 0:
        f = AlbaranForm()
        try:
            reg = Albaranes.objects.get(pk=id)
            f = AlbaranForm(request.POST, request.FILES, instance=reg)
        except Exception as e:
            print e
        if f.is_valid():
            reg = f.save()
            reg.save()
        else:
            print f.errors
        return redirect("Conta:lista_albaranes")
    else:
        f = AlbaranForm(request.POST, request.FILES)

        if f.is_valid():
            obj = f.save(commit=False)
            obj.cuenta_id = p.pk
            obj.save()
        else:
            print "error: "+ f.errors

        return redirect("Conta:lista_albaranes")


@login_required(login_url='login_tk')
def rm_albaran(request, id):
    try:
        obj = Albaranes.objects.get(pk=id)
        if obj.doc.name != "":
            os.remove(os.path.join(settings.MEDIA_ROOT, obj.doc.name))
        obj.delete()
    except Exception as e:
        print e

    return redirect("Conta:lista_albaranes")


@login_required(login_url='login_tk')
def lista_albaranes(request):
    obj = get_proveedor_activo(request)
    f = AlbaranForm()
    if request.method == "POST":
        filter = request.POST["filter"]
        filter_query = Albaranes.objects.filter(Q(cuenta_id=obj.pk) |
                                                Q(fecha__contains=filter) |
                                                Q(numero__contains=filter))
        return render(request, "contabilidad/albaranes/listado.html",
                      {'query': filter_query,
                       "form": f,
                       "p": obj,
                       "pk": -1,
                       "mensaje": "Albaran nuevo"})
    else:
        filter_query = Albaranes.objects.filter(Q(cuenta_id=obj.pk))
        return render(request, "contabilidad/albaranes/listado.html",
                      {'query': filter_query,
                       "form": f,
                       'p': obj,
                       "pk": -1,
                       "mensaje": "Albaran nuevo" })




@login_required(login_url='login_tk')
def find_albaran(request):
    if request.method == "POST":
        filter = request.POST["filter"]
        filter_query = Albaranes.objects.filter(Q(importe__contains=filter) |
                                                Q(fecha__contains=filter))
        return render(request, "contabilidad/albaranes/lista_ajax.html",
                      {'query': filter_query,
                       "opcion": 'find'})
    else:
        filter_query = Albaranes.objects.all()
        return render(request, "contabilidad/albaranes/lista_ajax.html",
                      {'query': filter_query,
                       "opcion": 'find'})

@login_required(login_url='login_tk')
def view_doc_albaran(request, id):
    print id
    try:
        obj = Albaranes.objects.get(pk=id)
    except Exception as e:
        print e
    file_rml = os.path.join(settings.MEDIA_ROOT, obj.doc.name )
    f = open(file_rml, "rb")
    response = HttpResponse(content_type='image/*')
    response['Content-Disposition'] = 'inline; filename="%s"' % os.path.basename(obj.doc.name)

    response.write(f.read())
    return response

def viewer_img_albaran(request, id):
    try:
        obj = Albaranes.objects.get(pk=id)
    except Exception as e:
        print e
    return render(request, "contabilidad/albaranes/image.html",{
        "obj": obj
    })


def get_proveedor_activo(request):
    pk = request.session["accion_pk_proveedor"] if 'accion_pk_proveedor' in request.session else 0
    obj = Proveedores()
    try:
        obj = Proveedores.objects.get(pk=pk)
    except Exception as e:
        print e

    return obj

service_web/contabilidad/views/balances.py
# @Author: Manuel Rodriguez <valle>
# @Date:   21-Jan-2018
# @Email:  valle.mrv@gmail.com
# @Last modified by:   valle
# @Last modified time: 21-Jan-2018
# @License: Apache license vesion 2.0

service_web/templates/contabilidad/ingresos/ingresos.html
{% extends "base_admin.html" %}
{% load global_tag %}
{% block content %}
<div class="bg-light d-flex justify-content-between page-header">
  <h2 class="">Gastos</h2>

</div>

<div class="bg-light p-3 mb-3">
  <div class="p-3">
    <h3>{{titulo}}</h3>
  </div>
  {% if form_error %}
    <div  class="alert alert-success alert-dismissable">
      <button aria-hidden="true" data-dismiss="alert" class="close" type="button"> × </button>
      {% for field, errors in form_error.items %}
        {% for error in errors %}
         <p>{{error}}</p>
        {% endfor %}
      {% endfor %}
      </div>
  {% endif %}
  <form id='form_main' method="post" autocomplete="off">
    <div class="row">
      {% for field in form %}
        <div class="form-group col-md-6">
          <label for="{{field.name}}">{{ field.label }}</label>
          {{ field|addcss:"form-control" }}
        </div>
      {% endfor %}
    </div>
    {% csrf_token %}


    <div class="form-group" style="padding-top: 5px;">
        <button class="btn btn-success" type="submit">Agregar</button>
    </div>
  </form>
</div>
{%endblock%}

service_web/templates/contabilidad/ingresos/lista_ajax.html
{% load global_tag %}
{% load conta_tag %}
{% if query %}
  <div id="content_main" class="bg-light p-3 mb-3 content-table">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Fecha</th>
          <th>Importe</th>
          <th class="text-center">Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for c in query %}
        <tr>
          <td>{{ c.fecha }}</td>
          <td>{{ c.importe }}</td>
          <td class="text-center">
            <a href="{% url 'en_construccion' %}" class="btn btn-primary btn-accion ">
              <span class="fa fa-search"></span></a>
            <a href="{% url 'Conta:ingresos' id=c.id %}" class="btn btn-primary btn-accion">
              <span class="fa fa-edit"></span></a>
            <a href="{% url 'Conta:rm_ingreso' id=c.id %}" class="btn btn-primary btn-accion">
                <span class="fa fa-trash"></span></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% else %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container pl-3">
          <h1 class="display-3">Upps!</h1>
          <p class="lead">No se ha encotrado ninguna coincidencia....</p>
      </div>
    </div>
{% endif %}

service_web/templates/contabilidad/ingresos/listado.html
{% extends "base_admin.html" %}
{% load global_tag %}
{% load static %}
{% block content %}
<div class="bg-light page-header">
  <div class="row">
    <div class="col-12 col-md-7">
      <h2>Ingresos</h2>
    </div>
    <div class="col-12 col-md-4">
      <form id="form_find" onsubmit="get_ingresos(); return false" class="form-inline my-2 my-lg-0" method="post">
          {% csrf_token %}
          <input class="form-control mr-sm-2" type="text" name="filter" placeholder="Buscar" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
          {% if not 'Editar' in mensaje %}
            <button class="btn btn-primary ml-2" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                  <span class="fa fa-plus"></span>
                </button>
          {% endif %}
      </form>
    </div>
  </div>
</div>

<div class="bg-light p-3 mb-3 {% if not 'Editar' in mensaje %} collapse {% endif %}" id="collapseExample">
  <div class="p-3">
    <h3>{{mensaje}}</h3>
  </div>
  <form method="post" action="{% url 'Conta:ingresos' id=pk %}" >
    {% csrf_token %}
    <div class="form-row">
        {% for field in form %}
          {% if field.name == 'fecha' %}
            <div class="form-group col-sm-6">
                <label for="{{field.name}}">{{ field.label }}</label>
                <div class='input-group date'>
                    {{ field|addcss:"form-control" }}
                    <span class="input-group-addon">
                        <span class="fa fa-calendar"></span>
                    </span>
                  </div>
              </div>
          {% else %}
          <div class="form-group col-md-6">
            <label for="{{field.name}}">{{ field.label }}</label>
            {{ field|addcss:"form-control" }}
          </div>
          {% endif %}
        {% endfor %}
      </div>
      <button type="submit" class="btn btn-primary">Enviar formulario</button>
      <button  onclick="calcular_ingreso(); return false;" class="btn btn-primary">Calcular ingresos</button>
  </form>
</div>

<div id="content_main" class="bg-light p-3 mb-3 content-table">
   {% include "contabilidad/ingresos/lista_ajax.html" %}
</div>


<script type="text/javascript">
    function calcular_ingreso(){
        fecha = $("#id_fecha").val();
        $.get("{% url 'Conta:calcular_ingreso_none' %}", {"fecha":fecha}, function(res){
          console.log(res.success)
           if(res.success){
             $("#id_importe").val(res.total);
           }

        })
    }

    function get_ingresos(){
      datos = $("#form_find").serialize();
      $.post("{% url 'Conta:find_ingreso' %}", datos, function(res){
          $("#content_main").html(res)
      });
      return false;
    }

    $('#id_fecha').pickadate({
      format: 'dd/mm/yyyy',
      formatSubmit: 'dd/mm/yyyy',
      hiddenName: true

    });


</script>

{% endblock content %}